# Generated by Django 5.2.6 on 2026-09-04 20:37

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddField(
            model_name='busyslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busyslot',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_slots', to='meetings.meeting'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['starts_at', 'ends_at'], name='meetings_me_starts__52d401_idx'),
        ),
        migrations.AddConstraint(
            model_name='busyslot',
            constraint=models.UniqueConstraint(fields=('meeting', 'user'), name='one_slot_per_meeting_user'),
        ),
        migrations.AddConstraint(
            model_name='busyslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('active', True)), expressions=(('user', '='), ('time_range', '&&')), name='prevent_overlapping_active_user_meetings'),
        ),
    ]
